name: _body_only
timestamp: 1499898304
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1472811520
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-4286: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-6854: Menu
  messages:
    system-messages-4003: 'System Messages'
  content:
    system-content-9686: 'Page Content'
  copyright:
    copyright-1070: Copyright
  spacer:
    spacer-1064: Spacer
  branding:
    branding-7966: Branding
  mobile-menu:
    mobile-menu-9254: Mobile-menu
inherit: {  }
