version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1472811520
layout:
  /header/:
    -
      - 'logo-4286 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-6854
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-4003
    -
      - system-content-9686
  /footer/:
    -
      - position-footer
    -
      - 'copyright-1070 40'
      - 'spacer-1064 30'
      - 'branding-7966 30'
  offcanvas:
    -
      - mobile-menu-9254
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
